baseURL = "https://t-jonoo.com"
title = "Takeshi JONOO Portfolio"
theme = "somrat"
# post pagination
pagination.pagerSize = "6"
# post excerpt
summaryLength = "10"
# disable language
# disableLanguages = [] # disable language from here
# google analutics
googleAnalytics = '' # example : UA-123-45
# disqus short name
# [[services.disqus.shortname]]
# shortname = "" # get your shortname form here : https://disqus.com
defaultContentLanguage = "fr"

############################# Outputs ##############################
[outputs]
home = ["HTML"]

[markup.goldmark.renderer]
unsafe= true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "https://api.fontshare.com/v2/css?f[]=general-sans@1&display=swap"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css2?family=Square+Peg&family=Kaisei+Tokumin:wght@800&family=Zen+Kaku+Gothic+Antique:wght@400;500&display=swap"
[[params.plugins.css]]
link = "plugins/flickity/flickity.css"
[[params.plugins.css]]
link = "plugins/flickity/flickity-fade.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/wow.min.js"
[[params.plugins.js]]
link = "plugins/flickity/flickity.pkgd.min.js"
[[params.plugins.js]]
link = "https://unpkg.com/flickity-fade@1/flickity-fade.js"
[[params.plugins.js]]
link = "plugins/isotope.pkgd.min.js"


#################### default parameters ################################
[params]
favicon = "images/favicon.png"
logo_light = ""
logo_dark = ""
logo_width = "100px"
# Meta data
description = "Official web site of Takeshi JONOO, Watercolor artist and Illustrator"
author = "takeshi jonoo"

# Preloader
[params.preloader]
enable = true
preloader = "" # use jpg, png, svg or gif format.

############################# social site ########################
# [[params.social]]
# icon = "fa-regular fa-envelope fa-xl"
# iconName = "envelope"
# link = "mailto:takeshi.jonoo@gmail.com"

[[params.social]]
icon = "fa-brands fa-facebook fa-xl"
iconName = "facebook"
link = "https://www.facebook.com/takeshi.jonoo"

[[params.social]]
icon = "fa-brands fa-instagram fa-xl"
iconName = "instagram"
link = "https://www.instagram.com/takeshi_jonoo_drawing"


################################### French language #####################################
[languages]
    [languages.fr]
        languageName = 'FR'
        languageCode = 'fr'
        contentDir = 'content/french'
        weight = 1
        [languages.fr.params]
        # copyright
        copyright = "&copy; [Takeshi JONOO](https://t-jonoo.com)<br>Copyright &copy; 2020 a hugo theme by [somrat](https://somrat.netlify.com)"


################# french navigation ##################
# main menu
        [[languages.fr.menu.main]]
        name = "Home"
        url = "#home"
        weight = 1

       [[languages.fr.menu.main]]
        name = "Recent works"
        url = "#portfolio"
        weight = 2

       [[languages.fr.menu.main]]
        name = "Portfolio"
        url = "portfolio"
        weight = 3

        [[languages.fr.menu.main]]
        name = "News"
        url = "#news"
        weight = 4

        [[languages.fr.menu.main]]
        name = "Presentation"
        url = "#about"
        weight = 5

        [[languages.fr.menu.main]]
        name = "Contact"
        url = "#contact"
        weight = 6

################################### jp language #####################################
    [languages.jp]
        languageName = "JP"
        languageCode = "jp"
        contentDir = "content/jp"
        weight = 2
        [languages.jp.params]
        # copyright
        copyright = "&copy; [Takeshi JONOO](https://t-jonoo.com)<br>Copyright &copy; 2020 a hugo theme by [somrat](https://somrat.netlify.com)"


################# jp navigation ##################
# main menu
        [[languages.jp.menu.main]]
        name = "ホーム"
        url = "#home"
        weight = 1

        [[languages.jp.menu.main]]
        name = "最近のお仕事"
        url = "#portfolio"
        weight = 2

        [[languages.jp.menu.main]]
        name = "ポートフォリオ"
        url = "portfolio"
        weight = 3

        [[languages.jp.menu.main]]
        name = "お知らせ"
        url = "#news"
        weight = 4

        [[languages.jp.menu.main]]
        name = "絵描き紹介"
        url = "#about"
        weight = 5

        [[languages.jp.menu.main]]
        name = "お問い合わせ"
        url = "#contact"
        weight = 6

################################### en language #####################################
    [languages.en]
        languageName = 'EN'
        languageCode = 'en'
        contentDir = 'content/en'
        weight = 3
        [languages.en.params]
        # copyright
        copyright = "&copy; [Takeshi JONOO](https://t-jonoo.com)<br>Copyright &copy; 2020 a hugo theme by [somrat](https://somrat.netlify.com)"


################# en navigation ##################
# main menu
        [[languages.en.menu.main]]
        name = "Home"
        url = "#home"
        weight = 1

       [[languages.en.menu.main]]
        name = "Recent works"
        url = "#portfolio"
        weight = 2

       [[languages.en.menu.main]]
        name = "Portfolio"
        url = "portfolio"
        weight = 3

        [[languages.en.menu.main]]
        name = "News"
        url = "#news"
        weight = 4

        [[languages.en.menu.main]]
        name = "About me"
        url = "#about"
        weight = 5

        [[languages.en.menu.main]]
        name = "Contact"
        url = "#contact"
        weight = 6