baseURL = "https://takejono.netlify.app"
title = "Takeshi JONOO Portfolio"
theme = "somrat"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disable language
disableLanguages = [] # disable language from here
# google analutics
googleAnalytics = "" # example : UA-123-45
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
defaultContentLanguage = 'fr'

############################# Outputs ##############################
[outputs]
home = ["HTML"]

[markup.goldmark.renderer]
unsafe= true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900&display=swap"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
[[params.plugins.css]]
link = "plugins/hover/hover.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/owl-carousel/owl.carousel.min.css"
[[params.plugins.css]]
link = "plugins/owl-carousel/owl.theme.default.min.css"
#[[params.plugins.css]]
#link = "plugins/text-animation/text-animation.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/wow.min.js"
#[[params.plugins.js]]
#link = "plugins/text-animation/text-animation.js"
[[params.plugins.js]]
link = "plugins/jquery.waypoints.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/owl-carousel/owl.carousel.min.js"


#################### default parameters ################################
[params]
favicon = "images/favicon.png"
logo_light = ""
logo_dark = ""
logo_width = "100px"
# Meta data
description = "This is meta description"
author = "takeshi jonoo"

# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

############################# social site ########################
[[params.social]]
icon = "fab fa-facebook"
link = "https://www.facebook.com/takeshi.jonoo"

[[params.social]]
icon = "fab fa-instagram"
link = "https://www.instagram.com/takeshi_jonoo_drawing"


################################### French language #####################################
[Languages.fr]
languageName = "Fr"
languageCode = "fr"
contentDir = "content/french"
weight = 1
home = "Home"
# copyright
copyright = "Copyright &copy; 2020 a hugo theme by [somrat](https://somrat.netlify.com)"


################# french navigation ##################

# main menu
[[Languages.fr.menu.main]]
name = "Home"
url = "/"
weight = 1

[[Languages.fr.menu.main]]
name = "Presentation"
pre = "#"
url = "about"
weight = 2

[[Languages.fr.menu.main]]
name = "Portfolio"
pre = "#"
url = "portfolio"
weight = 3

[[Languages.fr.menu.main]]
name = "Contact"
pre = "#"
url = "contact"
weight = 4

################################### English language #####################################
[Languages.jp]
languageName = "Jp"
languageCode = "jp"
contentDir = "content/jp"
weight = 2
home = "ホーム"
# copyright
copyright = "Copyright &copy; 2020 a hugo theme by [somrat](https://somrat.netlify.com)"


################# english navigation ##################

# main menu
[[Languages.jp.menu.main]]
name = "ホーム"
url = "/"
weight = 1

[[Languages.jp.menu.main]]
name = "私について"
pre = "#"
url = "about"
weight = 2

[[Languages.jp.menu.main]]
name = "ポートフォリオ"
pre = "#"
url = "portfolio"
weight = 3

[[Languages.jp.menu.main]]
name = "コンタクト"
pre = "#"
url = "contact"
weight = 4
